Feat - integrate omise to user payment
2110336-2565-2/sec2-group10-demo-backend pull request #57
Opened 2023-04-12 15:49 UTC by karnjj

**Changes**
- integrate omise to user payment
- re-structure upgrade to premium and wanna be artist endpoint

2023-04-13 08:45 UTC, pol-alones requested changes

2023-04-13 08:45 UTC, pol-alones commented on src/users/users.controller.ts
> +    await this.usersService.updateArtistBankAccount(req.user.userId, body);
Bug? since updateArtist function does check the role of artist first, but role artist is set after updateArtist.

2023-04-14 10:24 UTC, karnjj commented on src/users/users.controller.ts
> +    await this.usersService.updateArtistBankAccount(req.user.userId, body);
FIxed

2023-04-17 08:24 UTC, pol-alones approved these changes

2023-04-17 09:13 UTC, merged